---

#################################
# Tasks for configuring MongoDB #
#################################

# Defining tasks section.
- name: Configuring MongoDB server
  ansible.builtin.debug:
    msg: '[INFO] CONFIGURING MONGODB...'

- name: Creating configuration file
  ansible.builtin.copy:
    content: |
      storage:
        dbPath: /var/lib/mongodb
      systemLog:
        destination: file
        logAppend: true
        path: /var/log/mongodb/mongod.log
      net:
        port: {{ mongo_port }}
        bindIp: {{ mongo_ip }}
    dest: /etc/mongod.conf
    mode: u=rw,g=r,o=r
  notify: Restart service

- name: Setting kernel swap
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: 1

- name: Enable persistent swap
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: 'vm.swappiness = 1'
    state: present

- name: Setting firewall rule
  ansible.builtin.ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
    from_ip: "{{ system_ip }}"
    state: enabled
  loop: "{{ additional_ports }}"

#- name: Setting firewall rule
#  ansible.builtin.ufw:
#    rule: allow
#    proto: tcp
#    port: "{{ mongo_port }}"
#    from_ip: "{{ system_ip }}"
#    state: enabled

- name: Printing end status
  ansible.builtin.debug:
    msg: '[INFO] Finished, MongoDB configured.'
