---

##################################################################################
# An Ansible playbook to consolidate monolithic playbooks into a reusable roles. #
##################################################################################

# Defining target section.
- name: Applying Zabbix role
  hosts: localhost
  gather_facts: true
  become: true

# Defining roles section.
  roles: # Refers to the role directory.
    - zabbix
...
