---

##################################################################################
# An Ansible playbook to automate a Zabbix agent 2 installation on Ubuntu 20.04. #
##################################################################################

# Defining target section.
- name: Installing agent
  hosts: managed_nodes
  gather_facts: yes

# Defining variable section.
  vars:
    version: ubuntu20.04_all
    zabbix_server: 192.168.56.80
    agent_data: Linux
    agent_port: 10050

# Defining task section.
  tasks:
      - name: Copying script
        copy: 
          src: "scripts/uninstall.sh"
          dest: /opt/agent_uninstall.sh
          mode: u=rwx,g=w,o=r

      - name: Executing script
        command: bash /opt/agent_uninstall.sh
        run_once: false

      - name: Updating repositories
        apt:
          upgrade: no
          update_cache: yes
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

      - name: Downloading package
        get_url:
          url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1+{{ version }}.deb
          dest: /opt/Agent2-focal.deb
          mode: u=rw,g=w,o=r

      - name: Installing package
        apt:
          deb: /opt/Agent2-focal.deb
        ignore_errors: yes

      - name: Removing source
        file:
          path: /etc/apt/sources.list.d/zabbix.list
          state: absent

      - name: Updating source
        copy:
          dest: "/etc/apt/sources.list.d/zabbix.list"
          content: |
            deb [arch=amd64] http://repo.zabbix.com/zabbix/6.0/ubuntu focal main
            deb-src [arch=amd64] http://repo.zabbix.com/zabbix/6.0/ubuntu focal main

      - name: Installing agent
        apt:
          name: zabbix-agent2
          state: present
          update_cache: yes
        ignore_errors: yes

      - name: Stopping service
        systemd:
          name: zabbix-agent2
          state: stopped

      - name: Purging configuration
        file:
          path: /etc/zabbix/zabbix_agent2.conf
          state: absent

      - name: Applying configuration
        template:
          src: "templates/agent2.conf.j2"
          dest: "/etc/zabbix/zabbix_agent2.conf"
          mode: u=rw,g=w,o=r

      - name: Updating node hostname
        lineinfile:
          path: /etc/zabbix/zabbix_agent2.conf
          regexp: 'Hostname=ip-172-31-47-98'
          line: "Hostname=Ubuntu_node1"
        when: ansible_hostname == 'ip-172-31-47-98'

      - name: Updating node hostname
        lineinfile:
          path: /etc/zabbix/zabbix_agent2.conf
          regexp: 'Hostname=ip-172-31-65-21'
          line: "Hostname=Ubuntu_node2"
        when: ansible_hostname == 'ip-172-31-65-21'

      - name: Removing package
        file:
          path: /opt/Agent2-focal.deb
          state: absent

      - name: Allowing port
        ufw:
          rule: allow
          proto: tcp
          from_ip: 192.168.56.80
          to_port: 10050

      - name: Docker monitoring
        command: "chmod a=rw /var/run/docker.sock"
        ignore_errors: yes

      - name: Starting service
        systemd:
          name: zabbix-agent2
          state: started
          enabled: yes

        notify:
        - restart agent

      - name: Printing end status
        debug:
          msg: 'Finished, agent installed.'

# Defining handler section.
  handlers:
      - name: restart agent
        systemd:
          name: zabbix-agent2
          state: restarted
...
