---

##########################################################
# An Ansible playbook to install Docker on Ubuntu 20.04. #
##########################################################

# Defining target section.
- name: Install Docker and deploy Nginx
  hosts: localhost
  become: true
  gather_facts: yes

  # Defining task section.
  tasks:
    - name: Installing packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - curl
          - gnupg
        state: latest
        update_cache: true

    - name: Adding key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present

    - name: Adding repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: Updating system
      apt:
        update_cache: yes

    - name: Installing Docker
      apt:
        name: docker-ce
        state: latest
        ignore_errors: yes

    - name: Creating directory
      file:
        path: "/container"
        state: directory
        mode: 'u=rwx,g=rw,o=rw'

    - name: Deploying container
      docker_container:
        image: nginx:latest
        name: nginx
        state: started
        ports:
          - "8080:80"
        volumes:
          - "/container:/container"

    - name: End message
      debug:
        msg: 'Finished, application installed.'

...
