---

##########################################################################
# An Ansible playbook to automate a Docker installation on Ubuntu 20.04. #
##########################################################################

# Defining target section.
- name: Installing Docker
  hosts: all
  become: true
  gather_facts: yes

# Defining target section.
  tasks:
      - name: Installing packages
        apt:
          name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
          state: latest
        update_cache: true

      - name: Creating directories
        file: 
          path: "{{ item }}"
          state: directory
          mode: u=rwx,g=rw,o=rw
        with_items:
        - /container
        - /srv/scripts

      - name: Adding GPG key
        apt_key:
          url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
          state: present

      - name: Installing Docker
        apt_repository:
          repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker

      - name: Deploying container
        docker_container:
          image: nginx:latest
          name: nginx
          state: started
          ports:
            - "8080:80"
          volumes:
            - /container

      - name: Printing end status
        debug:
          msg: 'Finished, Application installed.'
...
