---

############################################################################
# Ansible playbook to install AIDE, Lynis and Fail2ban onto managed nodes. #
############################################################################

# Defining target section.
- name: Hardening systems
  hosts: managed_nodes
  gather_facts: yes
  become: yes

# Defining variable section.
  vars:
    bantime: 3600
    port: 22
    time: 300
    retry: 3
    email: sk3ma87@gmail.com

# Defining task section.
  tasks:
      - name: Upgrading repositories
        apt:
          upgrade: no
          update_cache: yes

      - name: Installing AIDE
        apt:
          name: aide
          state: present

      - name: Initializing AIDE
        command: "aideinit"

      - name: Making backup
        copy: 
          remote_src: true
          src: /var/lib/aide/aide.db.new
          dest: /var/lib/aide/aide.db
          owner: root
          group: root
          mode: u=rwx,g=w,o=r
          backup: yes

      - name: Creating directory
        file: 
          path: /root/TEST
          state: directory

      - name: Creating file
        file:
          path: /root/ADDED-NEW-FILE.txt
          state: touch
          mode: u=rw,g=r,o=r

      - name: Updating AIDE
        command: "update-aide.conf"

      - name: Copying file
        copy: 
          remote_src: true
          src: /var/lib/aide/aide.conf.autogenerated
          dest: /etc/aide/aide.conf
          owner: root
          group: root
          mode: u=rwx,g=w,o=r
          backup: yes

      - name: Updating configuration
        lineinfile:
          path: /etc/default/aide
          regexp: 'MAILTO=root'
          line: "MAILTO=sk3ma87@gmail.com"

      - name: Importing key
        apt_key:
          url: "https://packages.cisofy.com/keys/cisofy-software-public.key"
          state: present

      - name: Updating source
        copy:
          dest: "/etc/apt/sources.list.d/cisofy-lynis.list"
          content:
            deb https://packages.cisofy.com/community/lynis/deb/ stable main

      - name: Installing Lynis
        apt:
          name: lynis
          state: present
          update_cache: yes
        ignore_errors: yes

      - name: Installing Fail2ban
        apt:
          name: "{{ item }}"
          state: present
        with_items:
         - fail2ban
         - sendmail
         - vim
         - screenfetch
        when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

      - name: Removing permissions
        file:
          dest: /etc/update-motd.d
          mode: a-x

      - name: Updating shell
        shell: "echo '/usr/bin/screenfetch' >> /home/vagrant/.bashrc"

      - name: Applying configuration
        template:
          src: "templates/jail.local.j2"
          dest: "/etc/fail2ban/jail.local"
          owner: root
          group: root
          mode: u=rw,g=r,o=r

#      - name: Changing hostname
#        hostname:
#          name: "websrv01"

      - name: Updating shell
        lineinfile:
          create: yes
          mode: u=rw
          dest: ~/.bashrc
          owner: vagrant
          regexp: '^PS1='
          line: 'PS1="${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "'
          state: present

        notify:
        - restart service

      - name: Confirming status
        command: "fail2ban-client status sshd"

      - name: Printing message
        debug:
          msg: 'Finished, installation complete.'

# Defining handler section.
  handlers:
      - name: restart service
        systemd:
          name: fail2ban
          state: restarted
...
