---

#################################################################################
# This Ansible playbook will automate an HAProxy installation on Ubuntu 20.04.  #
# It adds the repository, fetches the GPG key and installs the HAProxy package. #
#################################################################################

# Defining target section.
- name: HAProxy installation
  hosts: localhost
  gather_facts: yes 
  become: true

# Defining task section.
  tasks:
    - name: Installing Netdata
      ansible.builtin.debug:
        msg: '[INFO] INSTALLING HAPROXY...'

    - name: Installing dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - gnupg2
        - ca-certificates
        - software-properties-common

    - name: Adding repsitory
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/haproxy.list
        create: yes
        line: "deb http://ppa.launchpad.net/vbernat/haproxy-2.6/ubuntu focal main"

    - name: Obtaining key
      aansible.builtin.apt_key:
        url: https://haproxy.debian.net/bernat.debian.org.gpg
        state: present
      register: value

    - name: Display key
      ansible.builtin.debug:
          msg: "The {{ value.fp }} fingerprint was added"

    - name: Installing HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: latest
        update_cache: yes

    - name: HAProxy version
      command: "haproxy -vv"
      register: results

    - name: Display version
      ansible.builtin.debug:
        msg: "{{ results.stdout }}"

    - name: Enabling service
      ansible.builtin.systemd:
        name: haproxy
        state: started
        enabled: yes
        notify:
        - restart proxy

    - name: End status
      ansible.builtin.debug:
        msg: '[INFO] Finished, HAProxy installed.'

# Defining handler section.
  handlers:
      - name: restart proxy
        ansible.builtin.systemd:
          name: haproxy
          state: restarted

      - name: End Ansible playbook
        ansible.builtin.meta: end_play
