---

###################################################################################
# This Ansible playbook will automate a Netdata installation on Ubuntu 20.04.     #
# It will uninstall the Netdata agent, configure it and add a firewall exception. #
###################################################################################

# Defining target section.
- name: Install and configure Netdata
  hosts: localhost
  become: true
  gather_facts: true


# Defining task section.
  tasks:
    - name: Installing Netdata
      ansible.builtin.debug:
        msg: '[INFO] INSTALLING NETDATA...'

    - name: Downloading script
      ansible.builtin.get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata-kickstart.sh

    - name: Executing script
      ansible.builtin.shell: bash /tmp/netdata-kickstart.sh --no-updates --stable-channel --disable-telemetry --native-only --no-updates --non-interactive --disable-cloud
      args:
        chdir: /tmp

    - name: Getting version
      ansible.builtin.command: netdata --version
      register: results
      changed_when: false

    - name: Showing version
      ansible.builtin.debug:
        msg: "{{ results.stdout }}"

    - name: Adding configuration
      ansible.builtin.lineinfile:
        path: /etc/netdata/netdata.conf
        line: "{{ item }}"
      loop:
        - "run as user = netdata"
        - "web files owner = root"
        - "web files group = root"
        - "bind socket to IP = 192.168.56.72"
      notify: Restart Netdata

    - name: Allowing rule
      ansible.builtin.ufw:
        rule: allow
        proto: tcp
        port: 19999
        state: enabled

    - name: Late commands
      ansible.builtin.command:
        cmd: |
          ufw reload
          sudo netdatacli reload-health 
      changed_when: false

    - name: Checking status
      ansible.builtin.systemd:
        name: netdata
        state: started
      register: netdata_status

    - name: Displaying status
      ansible.builtin.debug:
        var: netdata_status

    - name: End status
      ansible.builtin.debug:
        msg: '[INFO] Finished, Netdata installed.'

# Defining handler section.
  handlers:
    - name: Restart Netdata
      ansible.builtin.systemd:
        name: netdata
        state: restarted

    - name: End playbook
      ansible.builtin.meta: end_play
