---

#########################################################
# An Ansible playbook to install Nginx on Ubuntu 20.04. #
#########################################################

# Defining target section.
- name: Installing Nginx
  hosts: localhost
  become: true
  gather_facts: yes

 # Defining task section.
  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      ignore_errors: yes

    - name: Allowing service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Allowing HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allowing HTTPS
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: End message
      debug:
        msg: 'Finished, Nginx installed.'
...
