---

##################################################################################
# An Ansible playbook to consolidate monolithic playbooks into a reusable roles. #
##################################################################################

# Defining target section.
- name: Applying Nginx role
  hosts: localhost
#  remote_user: root
  gather_facts: true
  become: true

# Defining roles section.
  roles: # Refers to the role directory.
    - name: nginx
      tags: ['nginx']
...
