---

###########################################################
# An Ansible playbook to configure Nginx on Ubuntu 20.04. #
###########################################################

# Defining task section.
    - name: Configuring Nginx
      ansible.builtin.debug:
        msg: '[INFO] CONFIGURING NGINX...'

    - name: Applying configuration
      ansible.builtin.template:
        src: "templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: u=rw,g=w,o=r

    - name: Restarting Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: End message
      ansible.builtin.debug:
        msg: '[INFO] Finished, Nginx configured.'

    - name: End playbook
      ansible.builtin.meta: end_play
