---

#########################################################
# An Ansible playbook to install Nginx on Ubuntu 20.04. #
#########################################################

 # Defining task section.
    - name: Installing Nginx
      ansible.builtin.debug:
        msg: '[INFO] INSTALLING NGINX...'

    - name: Installing dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - gnupg2
        - ca-certificates

    - name: Installing Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      ignore_errors: no

    - name: Index file
      ansible.builtin.command: echo "<h1>Nginx is operational</h1>" > /usr/share/nginx/html/index.html

    - name: Get version
      ansible.builtin.shell: nginx -v
      register: results

    - name: Showing version
    - ansible.builtin.debug:
        msg: "{{ results.stderr }}"

    - name: Allowing service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
      notify:
      - restart nginx

    - name: Allowing HTTP
      ansible.builtin.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Allowing HTTPS
      ansible.builtin.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: End message
      ansible.builtin.debug:
        msg: '[INFO] Finished, Nginx installed.'
