---

###########################################################
# An Ansible playbook to configure Nginx on Ubuntu 20.04. #
###########################################################

# Defining target section.
- name: Configuring Nginx
  hosts: localhost
  become: true
  gather_facts: yes

# Defining variable section.
  vars:
    port: 80
    server: example.com

# Defining task section.
  tasks:
    - name: Applying configuration
      template:
        src: "templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: u=rw,g=w,o=r

    - name: Restarting Nginx
      systemd:
        name: nginx
        state: restarted

    - name: End message
      debug:
        msg: 'Finished, Nginx configured.'

    - meta: end_play
