---

##################################################################################
# An Ansible playbook to consolidate monolithic playbooks into a reusable roles. #
##################################################################################

# Defining target section.
- name: Apply role
  hosts: localhost # target_hosts
  become: yes
  gather_facts: yes

# Defining roles section.
  roles: # Refers to the role directory.
    - nginx
...
