name: Playbook functional testing

on:
  push:
    branches:
      - main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install yamllint ansible-lint -y
        shell: bash
        if: success()

      - name: Lint files
        id: yamllint
        run: |
          yamllint /opt/ansible
        continue-on-error: false
        shell: bash

      - name: Lint playbook
        id: ansiblelint
        run: |
          ansible-lint HAProxy.yml
        continue-on-error: false
        shell: bash

      - name: Checking results
        run: |
          if [[ ${{ steps.yamllint.outcome }} == "failure" || ${{ steps.ansiblelint.outcome }} == "failure" ]]; then
            echo "Linting failed, exiting..."
            exit 1
          else
            echo "Linting passed, proceeding..."
          fi
        shell: bash

      - name: Execute playbook
        run: |
          ansible-playbook HAProxy.yml
        shell: bash
